### ISSUE TITLE
how Install nms module in windows

### ISSUE THREAD

**Issue by ghost** [HsLOL/RetinaNet-PyTorch#2]
i can't run make in windows

**Comment by HsLOL** [comment]
Sorry, I had only compiled my code on linux systems.

**Comment by ghost** [comment]
ok , thank you


Shimaa Holail
Communication and Electronic Engineer
Mathematics and Physics Department
College of Engineering, Shoubra - Benha University
108 Shoubra St., Cairo - Egypt
Postal Code: 11629
Mobile: (002) 0100 288 2215
WhatsApp: (002) 0100 288 2215
WeChat ID: wxid_4wcff6av9p6t22
LinkedIn :https://www.linkedin.com/in/shimaaholail/
[cid:d8af11dd-91e5-412c-8ba8-3c33013e4cbb]
[cid:13280771-8a3f-4d5b-a685-1b91a459593b]

________________________________

**Comment by Guozt123** [comment]
> i can't run make in windows

This can be solved using MinGW.
